export { default } from "./src/wallet-manager-evm-7702-gasless.js";
export { default as WalletAccountReadOnlyEvm7702Gasless } from "./src/wallet-account-read-only-evm-7702-gasless.js";
export { default as WalletAccountEvm7702Gasless } from "./src/wallet-account-evm-7702-gasless.js";
export { ConfigurationError } from "./src/errors.js";
export type FeeRates = import("@tetherto/wdk-wallet-evm").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet-evm").KeyPair;
export type EvmTransaction = import("@tetherto/wdk-wallet-evm").EvmTransaction;
export type TransactionResult = import("@tetherto/wdk-wallet-evm").TransactionResult;
export type EvmTransferOptions = import("@tetherto/wdk-wallet-evm").EvmTransferOptions;
export type TransferResult = import("@tetherto/wdk-wallet-evm").TransferResult;
export type EvmTransactionReceipt = import("@tetherto/wdk-wallet-evm").EvmTransactionReceipt;
export type ApproveOptions = import("@tetherto/wdk-wallet-evm").ApproveOptions;
export type TypedData = import("@tetherto/wdk-wallet-evm").TypedData;
export type Evm7702GaslessWalletConfig = import("./src/wallet-manager-evm-7702-gasless.js").Evm7702GaslessWalletConfig;
export type Evm7702GaslessWalletCommonConfig = import("./src/wallet-account-read-only-evm-7702-gasless.js").Evm7702GaslessWalletCommonConfig;
export type Evm7702GaslessPaymasterTokenConfig = import("./src/wallet-account-read-only-evm-7702-gasless.js").Evm7702GaslessPaymasterTokenConfig;
export type Evm7702GaslessSponsorshipPolicyConfig = import("./src/wallet-account-read-only-evm-7702-gasless.js").Evm7702GaslessSponsorshipPolicyConfig;
